### ISSUE TITLE
Add your card in the website

### ISSUE THREAD

**Issue by aayushbisen** [we-developers-community/OpenSource-contributions#2]
Add your details as a card in the website.

### Steps

1- Open the index.html in your forked repo. 
2- Commit your changes and push to GitHub.
3- Open a pull request in this repo. 

Now, you can view your card in the website [here](https://oss101.netlify.app/) 🎉

**Comment by ashish11chawda** [comment]
Hey @aayushbisen , I want to work on this issue.
Can you please assign it to me!
