### ISSUE TITLE
Add header

### ISSUE THREAD

**Issue by aayushbisen** [we-developers-community/OpenSource-contributions#3]
Add a header in the website.

### Steps
1- Open the index.html in your forked repo.
2- Commit your changes and push to GitHub.
3- Open a pull request in this repo.

Now, you can view the changes in the website here 🎉

**Comment by KJCastillo** [comment]
Hey @aayushbisen i can create the header. Is there any specific you'd like in the header?

Also can you label this **hacktoberfest** and **hactoberfest-accepted** to get credit please.
